### ISSUE TITLE
Enhancement - DCCB as Docker Container

### ISSUE THREAD

**Issue by fahrenhe1t** [dopeghoti/DiscordCurrentlyCastingBot#14]
It would be cool if the DiscordCurrentlyCastingBot was created as a Docker container.  Easy to manage port access and configuration.  Should have the ability to set up a bind volume so database and config is stored on host machine, and is retained between reboots and upgrades.  Thanks for your consideration!

**Comment by dopeghoti** [comment]
Sounds like a good excuse for me to finally get off my duff and learn how to Docker (:
I'll certainly look into it!

**Comment by fahrenhe1t** [comment]
I got DiscordCurrentlyCastingBot to work as a Docker container on my home server.  I cloned your project to a folder, and filled out the .env with my server/channel info.  Then I use this Dockerfile to create the Docker image:
```
FROM python:3.7.13-alpine3.16

LABEL Maintainer="dopeghoti"

WORKDIR /opt/DiscordCurrentlyCastingBot/

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY bot.py ./
COPY channeldb.py ./
COPY currentlycastingbot-pm2.json ./

CMD [ "python", "./bot.py" ]
```

Then I build the docker image with: ``docker build -t discordcurrentlycastingbot:1.1 .``

Then I created a docker-compose.yml file to run it.  The environment variables in the docker-compose file get passed to the container from the .env file the user creates in the same folder:

```
---
version: "3"
services:
  dccb:
    image: discordcurrentlycastingbot:1.1
    container_name: discordcurrentlycastingbot
    environment:
      PUID: 1000
      PGID: 1000
      TZ: US/Mountain
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DISCORD_GUILD: "${DISCORD_GUILD}"
      DISCORD_PREFIX: "${DISCORD_PREFIX}"
      DISCORD_MONITOR: "${DISCORD_MONITOR}"
      DISCORD_CONTROL: "${DISCORD_CONTROL}"
      TWITCH_CLIENTID: "${TWITCH_CLIENTID}"
      TWITCH_SECRET: "${TWITCH_SECRET}"
      CHANNELS: "${CHANNELS}"
      WATCH_LENGTH: "${WATCH_LENGTH}"
    volumes:
      - ./config/${CHANNELS}:/opt/DiscordCurrentlyCastingBot/${CHANNELS}
    restart: unless-stopped
```
It maps the database to a bind volume so the data persists between restarts.
Then I run the docker container, and it's verified working on my end: ``docker compose up -d --force-recreate``

Maybe you could create the official image on your end and upload it to the github container repo (ghcr.io) or hub.docker.com?
